plugins {
    kotlin("jvm")
    kotlin("plugin.serialization")
    application
    // (ADR-007): fat JAR as the primary release artifact.
    id("com.gradleup.shadow")
}

application {
    mainClass.set("dev.bloopdex.contractlens.cli.MainKt")
    applicationName = "contractlens"
}

// Reproducibility (ADR-007): normalized entry timestamps and order so a
// rebuild from a clean checkout produces identical bytes — verified by
// the double-build check, any remaining nondeterminism is
// documented in docs/release.md.
tasks.shadowJar {
    archiveBaseName.set("contractlens")
    archiveClassifier.set("all")
    isPreserveFileTimestamps = false
    isReproducibleFileOrder = true
    manifest {
        attributes["Main-Class"] = "dev.bloopdex.contractlens.cli.MainKt"
    }
}

// The CLI version has exactly one authoritative source: `version` in
// the root build.gradle.kts. This task turns it into a generated Kotlin
// constant the CLI reports via `--version`; the release script and the
// release workflow verify the tag against the same literal.
val generateVersionInfo =
    tasks.register("generateVersionInfo") {
        val outputDir = layout.buildDirectory.dir("generated/version")
        val versionValue = project.version.toString()
        inputs.property("version", versionValue)
        outputs.dir(outputDir)
        doLast {
            val packageDir = outputDir.get().dir("dev/bloopdex/contractlens/cli").asFile
            packageDir.mkdirs()
            packageDir.resolve("VersionInfo.kt").writeText(
                """
                // Generated by :cli:generateVersionInfo — do not edit.
                package dev.bloopdex.contractlens.cli

                internal const val CONTRACTLENS_VERSION: String = "$versionValue"
                """.trimIndent() + "\n",
            )
        }
    }

sourceSets {
    main {
        kotlin.srcDir(generateVersionInfo)
    }
}

tasks.compileKotlin {
    dependsOn(generateVersionInfo)
}

dependencies {
    implementation(project(":core"))
    implementation(project(":openapi-parser"))
    implementation(project(":snapshot-store"))
    implementation(project(":registry"))
    implementation(project(":generated-client"))
    implementation(project(":graphql"))
    implementation(project(":json-schema"))

    implementation("com.github.ajalt.clikt:clikt:5.0.3")
    implementation("org.slf4j:slf4j-api:2.0.16")
    // logback + the logstash JSON encoder are implementation deps:
    // the CLI sets the log level and emits structured kv events directly.
    implementation("ch.qos.logback:logback-classic:1.5.18")
    implementation("net.logstash.logback:logstash-logback-encoder:8.1")

    testImplementation(kotlin("test"))
    testImplementation("io.kotest:kotest-runner-junit5:5.9.1")
    testImplementation("io.kotest:kotest-assertions-core:5.9.1")
    testImplementation("com.github.ajalt.clikt:clikt:5.0.3")
}

// Fuzz suites: the same fuzz tests as the normal run, with a
// higher iteration count. `gradlew :cli:fuzz -PfuzzIterations=200000`
// runs a recorded large sweep; findings become regression tests.
tasks.register<Test>("fuzz") {
    description = "Runs the parser and classifier fuzz suites with the configured iteration count"
    group = "verification"
    testClassesDirs =
        sourceSets.test
            .get()
            .output.classesDirs
    classpath = sourceSets.test.get().runtimeClasspath
    systemProperty("fuzz.iterations", project.findProperty("fuzzIterations")?.toString() ?: "2000")
    filter { includeTestsMatching("*FuzzTest") }
    testLogging { events("failed") }
}
